name: school

# flutter build apk --no-sound-null-safety
version: "1.1.45+65"
publish_to: none

environment:
  sdk: ^2.14.3
  flutter: ^2.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  toast: 0.1.5
  flutter_hooks: 0.18.0
  permission_handler: 8.2.2
  get_it: 7.2.0
  rxdart: 0.27.2
  scrollable_positioned_list: 0.2.0-nullsafety.0
  audio_session: 0.1.6+1
  audioplayers: 0.20.1
  audio_service: 0.18.0
  #  video_player: 2.2.0
  wakelock: 0.5.6
  firebase: 9.0.2
  firebase_core: 1.7.0
  firebase_analytics: 8.3.3
  firebase_auth: 3.1.3
  firebase_crashlytics: 2.2.3
  firebase_database: 8.0.0
  firebase_performance: 0.7.1+1
  firebase_remote_config: 0.11.0+1
  firebase_storage: 10.0.5
  cloud_firestore: 2.5.3
  cloud_functions: 3.0.4
  flutter_masked_text: 0.8.0
  url_launcher: 6.0.12
  date_format: 2.0.4
  flutter_svg: 0.22.0
  lottie: 1.2.1
  path_provider: 2.0.5
  shared_preferences: 2.0.8
  dio: 4.0.0
  equatable: 2.0.3
  mp3_info: 0.2.0
  flutter_vector_icons: 1.0.0
  dart_tags: # 0.3.1
    git: https://github.com/maxeema/dart-tags # override for version compatibility cuz the package is no longer supported
  just_audio: 0.9.12
  dart_midi: 1.0.1
  flutter_bloc: 7.3.0
  bloc: 7.2.1
  hv_progress_indicator: 1.0.2
  functional_listener: 2.0.2
  flutter_html: 2.1.5
  velocity_x: 3.3.0
  string_extensions: 0.3.3
  dartx: 0.7.1
  sized_context: 1.0.0+1
  universal_platform: 1.0.0+1
  flutter_float_widget: 1.0.0
  collection: 1.15.0
  stack: 0.2.1
  blur: 3.0.0
  freezed_annotation: 0.15.0
  transparent_image: 2.0.0
  connectivity_plus: 2.0.2
  share_plus: 3.0.2
  package_info_plus: 1.3.0
  dartz: 0.10.0 # us classes like Tuple2, Either, Option. TODO: use Either<Failure, R> as the return type in by repos instead of success or throwing an exception
  #kt_dart: 0.9.1 # TODO refactor learn module to use KtList as immutable type using it as return type instead of Dart's List
  injectable: 1.5.0
  pedantic: 1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.4
  json_serializable: 5.0.2
  freezed: 0.15.0+1
  injectable_generator: 1.5.2
  flutter_lints: 1.0.4
#  lints: 1.0.1

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en

flutter:

  uses-material-design: true

  assets:
    - assets/pics/
    - assets/pics/cube/
    - assets/pics/imgslib/
    - assets/snds/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: Terminal
      fonts:
        - asset: assets/fonts/terminal.ttf
